version: '3.8'

services:
  rest-server:
    build:
      context: ./spring-ocr
    container_name: spring-ocr
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ocr
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: rabbitmq
      SPRING_RABBITMQ_PASSWORD: rabbitmq
      FILE_STORAGE_DIRECTORY: /app/storage/documents
      MINIO_URL: http://minio:9000
      MINIO_BUCKET_NAME: ocr-bucket
      MINIO_ACCESS_KEY: gMbdK6OJRhNnq5PYSxLJ
      MINIO_SECRET_KEY: ZCB9ceGSxDmk48YwM26ixzrpoF7E9Xx5dXKJhnoo
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: ./react-ocr
    container_name: react-frontend
    ports:
      - "80:80"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      SPRING_URL: "http://spring-ocr:8081"
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ocr
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  ocr-worker:
    build:
      context: ./ocr-worker
    container_name: ocr-worker
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: rabbitmq
      RABBITMQ_PASSWORD: rabbitmq
      MINIO_URL: http://minio:9000
      MINIO_BUCKET_NAME: ocr-bucket
      MINIO_ACCESS_KEY: gMbdK6OJRhNnq5PYSxLJ
      MINIO_SECRET_KEY: ZCB9ceGSxDmk48YwM26ixzrpoF7E9Xx5dXKJhnoo
    depends_on:
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - app-network

  minio:
    build:
      context: ./minio
    container_name: minio
    ports:
      - "9000:9000" 
      - "9001:9001" 
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
    volumes:
      - minio-data:/data 
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  minio-data:
    driver: local